In [59]:
import pandas as pd

bios = pd.read_csv('./bios.csv')

In [60]:
bios.dropna(subset=['died_date'], inplace=True)
bios['died_date'] = pd.to_datetime(bios['died_date'])
bios.sort_values(by='died_date', ascending=False)

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
26301,26495,Shahar-ud-Din Abdullah,1948-09-29,NaN,NaN,NaN,Malaysia,NaN,NaN,2023-12-28
71589,72131,Armando Sardi,1940-09-15,Monza,Monza e Brianza,ITA,Italy,174.0,72.0,2023-12-22
37924,38225,Martin Feeley,1950-08-13,NaN,NaN,NaN,Ireland,185.0,87.0,2023-12-21
72812,73366,Tambusamy Krishnan,1944-07-08,Penang,Pulau Pinang,MAS,Malaysia,180.0,67.0,2023-12-20
7684,7725,Janusz Gortat,1948-11-05,Brzozów,Podkarpackie,POL,Poland,186.0,81.0,2023-12-19
...,...,...,...,...,...,...,...,...,...,...
17780,17901,Joseph Olivier,1874-12-02,Paris VIe,Paris,FRA,France,180.0,74.0,1901-05-21
79630,80248,Charles Amberger,1882-01-09,Paris XVIIIe,Paris,FRA,France,NaN,NaN,1901-05-02
61088,61530,Selwin Calverley,1855-07-04,Leeds,England,GBR,Great Britain,NaN,NaN,1900-12-30
21605,21757,Edmond Brassart,1870-03-05,Paris Ve,Paris,FRA,France,NaN,NaN,1900-08-19
62432,62895,Édouard Mantois,1848-08-23,Blois,Loir-et-Cher,FRA,France,NaN,NaN,1900-04-23

In [61]:
bios[['FirstName', 'LastName']] = bios['name'].str.split(n=1, expand=True)
bios

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,FirstName,LastName
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,Jean-François,Blanchy
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17,Jean,Borotra
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20,Jacques,Brugnon
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25,Albert,Canet
7,8,Henri Cochet,1901-12-14,Villeurbanne,Rhône,FRA,France,NaN,NaN,1987-04-02,Henri,Cochet
...,...,...,...,...,...,...,...,...,...,...,...,...
145435,149158,Patrick Gasienica,1998-11-28,McHenry,Illinois,USA,United States,NaN,NaN,2023-06-12,Patrick,Gasienica
145492,149219,Carlos García-Ordóñez,1927-04-24,La Habana (Havana),Ciudad de La Habana,CUB,Cuba,NaN,NaN,2019-11-24,Carlos,García-Ordóñez
145494,149221,George Wright,1890-07-21,Toronto,Ontario,CAN,Canada,183.0,NaN,1973-01-28,George,Wright
145498,149225,André Foussard,1899-05-19,Niort,Deux-Sèvres,FRA,France,166.0,NaN,1986-03-18,André,Foussard
145499,149814,Bill Phillips,1913-07-15,Dulwich Hill,New South Wales,AUS,Australia,NaN,NaN,2003-10-20,Bill,Phillips

In [65]:
bios[(bios['NOC'] == 'Poland') & (bios['FirstName'] == 'Robert')]

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,FirstName,LastName
10460,10516,Robert Ruszkowski,1942-06-09,Warszawa (Warsaw),Mazowieckie,POL,Poland,187.0,80.0,1998-07-16,Robert,Ruszkowski
52517,52891,Robert Malinowski,1957-03-01,Warszawa (Warsaw),Mazowieckie,POL,Poland,195.0,87.0,2021-12-08,Robert,Malinowski
85460,86141,Robert Góralczyk,1943-03-21,Wyry,Śląskie,POL,Poland,169.0,72.0,1984-05-18,Robert,Góralczyk

In [71]:
bios.loc[1:5]

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,FirstName,LastName
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17,Jean,Borotra
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20,Jacques,Brugnon
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25,Albert,Canet